apiVersion: batch/v2alpha1
kind: CronJob
metadata:
  name: pg-dump-backup-cron-dev
  namespace: dinsic-aplus
  labels:
    env: dev
spec:
  concurrencyPolicy: Allow
  failedJobsHistoryLimit: 6
  jobTemplate:
    metadata:
      labels:
        env: dev
    spec:
      template:
        metadata:
          labels:
            parent: pg-dump-backup-job
            env: dev
        spec:
          containers:
            - env:
                - name: DATABASE_URL
                  valueFrom:
                    secretKeyRef:
                      key: database-url
                      name: aplus-preprod
                - name: DATABASE_NAME
                  value: aplus-preprod
                - name: DATABASE_BACKUP_PATH
                  value: /var/backups
                - name: RETENTION_DAYS
                  value: "30"
                - name: RECIPIENT_PUBLIC_KEY_B64
                  value: ???
                - name: RECIPIENT_PUBLIC_KEY_EMAIL
                  value: ???
                - name: AWS_ACCESS_KEY_ID
                  valueFrom:
                    secretKeyRef:
                      key: aws-access-key-id
                      name: aplus-aws-s3-preprod
                - name: AWS_SECRET_ACCESS_KEY
                  valueFrom:
                    secretKeyRef:
                      key: aws-secret-access-key
                      name: aplus-aws-s3-preprod
                - name: AWS_DEFAULT_REGION
                  valueFrom:
                    secretKeyRef:
                      key: aws-default-region
                      name: aplus-aws-s3-preprod
                - name: AWS_BUCKET_NAME
                  valueFrom:
                    secretKeyRef:
                      key: aws-bucket-name
                      name: aplus-aws-s3-preprod
              image: 172.30.8.127:5000/dinsic-aplus/pg-dump-backup:dev
              imagePullPolicy: Always
              name: pg-dump-backup
              resources:
                limits:
                  cpu: 250m
                  memory: 256Mi
                requests:
                  cpu: 250m
                  memory: 256Mi
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
              volumeMounts:
                - mountPath: /var/backups
                  name: db-backups
          dnsPolicy: ClusterFirst
          restartPolicy: OnFailure
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
          volumes:
            - name: db-backups
              persistentVolumeClaim:
                claimName: aplus-prep-prod-files
  schedule: "* */24 * * *"
  successfulJobsHistoryLimit: 30
  suspend: false